<a href="https://colab.research.google.com/github/abhinavpy/Tensorflow-Keras-Tutorials/blob/master/PyTorch_Tutorials.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from __future__ import print_function
import torch

In [0]:
x = torch.empty(5,3)
print(x)

tensor([[5.3559e-37, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 1.5975e-43],
        [1.1578e+27, 1.1362e+30, 7.1547e+22],
        [4.5828e+30, 1.2121e+04, 7.1846e+22],
        [9.2198e-39, 2.8892e+29, 2.6222e+20]])


In [0]:
x = torch.rand(5,3)
print(x)

tensor([[0.5464, 0.7821, 0.9462],
        [0.8174, 0.5849, 0.5788],
        [0.9098, 0.8408, 0.5507],
        [0.0922, 0.4684, 0.6513],
        [0.0994, 0.7620, 0.0165]])


In [0]:
x = torch.zeros(5,3,dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [0]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [0]:
x = x.new_ones(5, 3, dtype=torch.double)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [0]:
x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[-0.1548,  0.1950, -1.1871],
        [-0.8904,  0.4977,  0.5376],
        [ 1.4379, -1.2628, -0.5804],
        [-0.2108, -1.1878, -1.2929],
        [-1.1148,  0.2118,  0.4089]])


In [0]:
print(x.size())

torch.Size([5, 3])


In [0]:
y = torch.rand(5,3)
print(x + y)

tensor([[ 0.5368,  0.9329, -0.8066],
        [-0.1985,  1.0988,  0.7683],
        [ 1.9817, -0.5355,  0.2124],
        [-0.1832, -0.6979, -0.5896],
        [-0.5534,  1.1983,  0.6714]])


In [0]:
print(torch.add(x,y))

tensor([[ 0.5368,  0.9329, -0.8066],
        [-0.1985,  1.0988,  0.7683],
        [ 1.9817, -0.5355,  0.2124],
        [-0.1832, -0.6979, -0.5896],
        [-0.5534,  1.1983,  0.6714]])


In [0]:
y.add_(x)

tensor([[ 0.5368,  0.9329, -0.8066],
        [-0.1985,  1.0988,  0.7683],
        [ 1.9817, -0.5355,  0.2124],
        [-0.1832, -0.6979, -0.5896],
        [-0.5534,  1.1983,  0.6714]])

In [0]:
print(x[:, 1])

tensor([ 0.1950,  0.4977, -1.2628, -1.1878,  0.2118])


In [0]:
x = torch.randn(4,4)
print(x)
y = x.view(16)
print(y)
z = x.view(-1,8)
print(z)
print(x.size(), y.size(), z.size())

tensor([[-2.1417, -2.2757,  0.1198,  0.4732],
        [-0.2460,  0.7163, -1.3119,  0.3899],
        [ 0.2144, -0.4295, -0.5241, -1.4687],
        [ 0.4778, -0.5544, -2.8772,  1.4111]])
tensor([-2.1417, -2.2757,  0.1198,  0.4732, -0.2460,  0.7163, -1.3119,  0.3899,
         0.2144, -0.4295, -0.5241, -1.4687,  0.4778, -0.5544, -2.8772,  1.4111])
tensor([[-2.1417, -2.2757,  0.1198,  0.4732, -0.2460,  0.7163, -1.3119,  0.3899],
        [ 0.2144, -0.4295, -0.5241, -1.4687,  0.4778, -0.5544, -2.8772,  1.4111]])
torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [0]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([2.0996])
2.0996251106262207


In [0]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.5914])
0.5913953185081482


In [0]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [0]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [0]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [0]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [0]:
if torch.cuda.is_available():
    device = torch.device("cuda")          # A CUDA Device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings .to("cuda")
    z = x + y                              
    print(z)
    print(z.to("cpu", torch.double))       # .to() can also use dtype altogether

tensor([1.5914], device='cuda:0')
tensor([1.5914], dtype=torch.float64)


## Autograd Automatic Differentiation
Central to all neural networks is the autograd package. The ```autograd``` package provides automatic differentiation for all operations on tensors. It is a define-by-run framework which means that your backpropag is defined by how you run it.

In [0]:
import torch

In [2]:
x = torch.ones(2,2,requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [3]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [4]:
print(y.grad_fn)

In [5]:
z = y * y * 3
out = z.mean()

print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [7]:
a = torch.randn(2,2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


In [8]:
import torch

num_entries = 5000

db = torch.rand(num_entries) > 0.5
db

tensor([0, 0, 1,  ..., 1, 1, 0], dtype=torch.uint8)

In [9]:
db

tensor([0, 0, 1,  ..., 1, 1, 0], dtype=torch.uint8)

In [10]:
db.shape

torch.Size([5000])

In [11]:
db[0:5]

tensor([0, 0, 1, 1, 0], dtype=torch.uint8)

In [0]:
remove_index = 2

In [13]:
db[0:2]

tensor([0, 0], dtype=torch.uint8)

In [14]:
db[3:]

tensor([1, 0, 1,  ..., 1, 1, 0], dtype=torch.uint8)

In [15]:
torch.cat((db[0:2],db[3:]))[0:5]

tensor([0, 0, 1, 0, 1], dtype=torch.uint8)

In [0]:
def get_parallel_db(db, remove_index):
    return torch.cat((db[0:remove_index], db[remove_index+1:]))

In [17]:
get_parallel_db(db,3)

tensor([0, 0, 1,  ..., 1, 1, 0], dtype=torch.uint8)

In [0]:
def get_parallel_dbs(db):
    parallel_dbs = list()

    for i in range(len(db)):
        pdb = get_parallel_db(db, i)
        parallel_dbs.append(pdb)
        
    return parallel_dbs

In [0]:
pdbs = get_parallel_dbs(db)

In [25]:
len(pdbs)

5000

In [0]:
def create_db_and_parallels(num_entries):
    
    db = torch.rand(num_entries) > 0.5
    pdbs = get_parallel_dbs(db)
    
    return db, pdbs

In [0]:
db, pdbs = create_db_and_parallels(20)

In [28]:
db

tensor([0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0],
       dtype=torch.uint8)

In [29]:
pdbs

[tensor([0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0],
        dtype=torch.uint8),
 tensor([0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0],
        dtype=torch.uint8),
 tensor([0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0],
        dtype=torch.uint8),
 tensor([0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0],
        dtype=torch.uint8),
 tensor([0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0],
        dtype=torch.uint8),
 tensor([0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0],
        dtype=torch.uint8),
 tensor([0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0],
        dtype=torch.uint8),
 tensor([0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0],
        dtype=torch.uint8),
 tensor([0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0],
        dtype=torch.uint8),
 tensor([0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0],
        dtype=torch.uint8),
 tensor([0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0,

In [0]:
def query(db):
    return db.sum()

In [31]:
query(db)

tensor(8)